[package]
name = "virtio"
version = "0.1.0"
edition = "2021"

[dependencies]
twizzler-net = { path = "../../lib/twizzler-net" }
twizzler-object = { path = "../../lib/twizzler-object" }
twizzler-async = { path = "../../lib/twizzler-async" }
twizzler-driver = { path = "../../lib/twizzler-driver" }
twizzler-abi = { path = "../../lib/twizzler-abi", features = ["runtime"] }

virtio-drivers = "0.7.5"
volatile = { version = "0.5", features = ["unstable"] }
once_cell = "1.19.0"
fragile = "2.0.0"

[dependencies.smoltcp]
version = "0.11.0"
optional = false
default-features = true
features = [
  "alloc", "log",
  "medium-ethernet",
  "proto-ipv4",
  "socket-raw", "socket-icmp", "socket-udp", "socket-tcp",
]

[package.metadata]
twizzler-build = "static"